[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "llm-fleet"
version = "1.0.0"
authors = [
  { name="Oleksii Streltsov", email="streltsov2609@gmail.com" },
]
description = """
Fleet🚀 is an algorithm for distributed test-time scaling of LLM workflows
that use local models and can evaluate and rank generated completions.
"""
readme = "README.md"
license = "MIT"
license-files = ["LICEN[CS]E*"]
dependencies = [
    "pydantic",
    "torch"
]

[project.optional-dependencies]
priors = [
    "scikit-learn",
    "numpy"
]
vis = [
    "tokenizers",
    "pyvis"
]
all = [
    "scikit-learn",
    "numpy",
    "tokenizers",
    "pyvis"
]

[project.urls]
Homepage = "https://github.com/Alexiush/fleet"
Repository = "https://github.com/Alexiush/fleet.git"
Issues = "https://github.com/Alexiush/fleet/issues"