[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "fleet"
version = "0.1.0"
dependencies = [
    "pydantic",
    "torch"
]
description = """
Fleet🚀 is an algorithm for distributed test-time scaling of LLM workflows
that use local models and have verifiable rewards.
"""
readme = "README.md"

[project.optional-dependencies]
priors = [
    "scikit-learn",
    "numpy"
]
vis = [
    "tokenizers",
    "pyvis"
]
all = [
    "scikit-learn",
    "numpy",
    "tokenizers",
    "pyvis"
]

[project.urls]
Homepage = "https://github.com/Alexiush/fleet"
Repository = "https://github.com/Alexiush/fleet.git"
Issues = "https://github.com/Alexiush/fleet/issues"